# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""bmiInitializeRequest

    BmiInitializeRequest(;
        config_file=nothing,
    )

    - config_file::String
"""
Base.@kwdef mutable struct BmiInitializeRequest <: OpenAPI.APIModel
    config_file::Union{Nothing, String} = nothing

    function BmiInitializeRequest(config_file, )
        OpenAPI.validate_property(BmiInitializeRequest, Symbol("config_file"), config_file)
        return new(config_file, )
    end
end # type BmiInitializeRequest

const _property_types_BmiInitializeRequest = Dict{Symbol,String}(Symbol("config_file")=>"String", )
OpenAPI.property_type(::Type{ BmiInitializeRequest }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_BmiInitializeRequest[name]))}

function check_required(o::BmiInitializeRequest)
    true
end

function OpenAPI.validate_property(::Type{ BmiInitializeRequest }, name::Symbol, val)
end
