# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""bmiSetValueAtIndicesRequest

    BmiSetValueAtIndicesRequest(;
        indices=nothing,
        values=nothing,
    )

    - indices::Vector{Int64}
    - values::Vector{Float64}
"""
Base.@kwdef mutable struct BmiSetValueAtIndicesRequest <: OpenAPI.APIModel
    indices::Union{Nothing, Vector{Int64}} = nothing
    values::Union{Nothing, Vector{Float64}} = nothing

    function BmiSetValueAtIndicesRequest(indices, values, )
        OpenAPI.validate_property(BmiSetValueAtIndicesRequest, Symbol("indices"), indices)
        OpenAPI.validate_property(BmiSetValueAtIndicesRequest, Symbol("values"), values)
        return new(indices, values, )
    end
end # type BmiSetValueAtIndicesRequest

const _property_types_BmiSetValueAtIndicesRequest = Dict{Symbol,String}(Symbol("indices")=>"Vector{Int64}", Symbol("values")=>"Vector{Float64}", )
OpenAPI.property_type(::Type{ BmiSetValueAtIndicesRequest }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_BmiSetValueAtIndicesRequest[name]))}

function check_required(o::BmiSetValueAtIndicesRequest)
    true
end

function OpenAPI.validate_property(::Type{ BmiSetValueAtIndicesRequest }, name::Symbol, val)
end
