# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.

struct SettersApi <: OpenAPI.APIClientImpl
    client::OpenAPI.Clients.Client
end

"""
The default API base path for APIs in `SettersApi`.
This can be used to construct the `OpenAPI.Clients.Client` instance.
"""
basepath(::Type{ SettersApi }) = "http://localhost:50051"

const _returntypes_set_value_SettersApi = Dict{Regex,Type}(
    Regex("^" * replace("204", "x"=>".") * "\$") => Nothing,
    Regex("^" * replace("0", "x"=>".") * "\$") => ProblemDetails,
)

function _oacinternal_set_value(_api::SettersApi, name::String, request_body::Vector{Float64}; _mediaType=nothing)
    OpenAPI.validate_param("name", "set_value", :minLength, name, 1)

    _ctx = OpenAPI.Clients.Ctx(_api.client, "POST", _returntypes_set_value_SettersApi, "/set_value/{name}", [], request_body)
    OpenAPI.Clients.set_param(_ctx.path, "name", name)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? ["application/json", ] : [_mediaType])
    return _ctx
end

@doc raw"""Set the value of a variable.

Params:
- name::String (required)
- request_body::Vector{Float64} (required)

Return: Nothing, OpenAPI.Clients.ApiResponse
"""
function set_value(_api::SettersApi, name::String, request_body::Vector{Float64}; _mediaType=nothing)
    _ctx = _oacinternal_set_value(_api, name, request_body; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function set_value(_api::SettersApi, response_stream::Channel, name::String, request_body::Vector{Float64}; _mediaType=nothing)
    _ctx = _oacinternal_set_value(_api, name, request_body; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_set_value_at_indices_SettersApi = Dict{Regex,Type}(
    Regex("^" * replace("204", "x"=>".") * "\$") => Nothing,
    Regex("^" * replace("0", "x"=>".") * "\$") => ProblemDetails,
)

function _oacinternal_set_value_at_indices(_api::SettersApi, name::String, set_value_at_indices_request::SetValueAtIndicesRequest; _mediaType=nothing)
    OpenAPI.validate_param("name", "set_value_at_indices", :minLength, name, 1)

    _ctx = OpenAPI.Clients.Ctx(_api.client, "POST", _returntypes_set_value_at_indices_SettersApi, "/set_value_at_indices/{name}", [], set_value_at_indices_request)
    OpenAPI.Clients.set_param(_ctx.path, "name", name)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? ["application/json", ] : [_mediaType])
    return _ctx
end

@doc raw"""Set the value of a variable at specific indices.

Params:
- name::String (required)
- set_value_at_indices_request::SetValueAtIndicesRequest (required)

Return: Nothing, OpenAPI.Clients.ApiResponse
"""
function set_value_at_indices(_api::SettersApi, name::String, set_value_at_indices_request::SetValueAtIndicesRequest; _mediaType=nothing)
    _ctx = _oacinternal_set_value_at_indices(_api, name, set_value_at_indices_request; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function set_value_at_indices(_api::SettersApi, response_stream::Channel, name::String, set_value_at_indices_request::SetValueAtIndicesRequest; _mediaType=nothing)
    _ctx = _oacinternal_set_value_at_indices(_api, name, set_value_at_indices_request; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

export set_value
export set_value_at_indices
