# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""SetValueAtIndicesRequest

    SetValueAtIndicesRequest(;
        indices=nothing,
        values=nothing,
    )

    - indices::Vector{Int64}
    - values::Vector{Float64}
"""
Base.@kwdef mutable struct SetValueAtIndicesRequest <: OpenAPI.APIModel
    indices::Union{Nothing, Vector{Int64}} = nothing
    values::Union{Nothing, Vector{Float64}} = nothing

    function SetValueAtIndicesRequest(indices, values, )
        OpenAPI.validate_property(SetValueAtIndicesRequest, Symbol("indices"), indices)
        OpenAPI.validate_property(SetValueAtIndicesRequest, Symbol("values"), values)
        return new(indices, values, )
    end
end # type SetValueAtIndicesRequest

const _property_types_SetValueAtIndicesRequest = Dict{Symbol,String}(Symbol("indices")=>"Vector{Int64}", Symbol("values")=>"Vector{Float64}", )
OpenAPI.property_type(::Type{ SetValueAtIndicesRequest }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_SetValueAtIndicesRequest[name]))}

function check_required(o::SetValueAtIndicesRequest)
    o.indices === nothing && (return false)
    o.values === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ SetValueAtIndicesRequest }, name::Symbol, val)
end
