# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.

@doc raw"""GetVarTypeResponse

    GetVarTypeResponse(;
        type=nothing,
    )

    - type::String
"""
Base.@kwdef mutable struct GetVarTypeResponse <: OpenAPI.APIModel
  type::Union{Nothing, String} = nothing

  function GetVarTypeResponse(type)
    OpenAPI.validate_property(GetVarTypeResponse, Symbol("type"), type)
    return new(type)
  end
end # type GetVarTypeResponse

const _property_types_GetVarTypeResponse = Dict{Symbol, String}(Symbol("type") => "String")
OpenAPI.property_type(::Type{GetVarTypeResponse}, name::Symbol) =
  Union{Nothing, eval(Base.Meta.parse(_property_types_GetVarTypeResponse[name]))}

function check_required(o::GetVarTypeResponse)
  o.type === nothing && (return false)
  true
end

function OpenAPI.validate_property(::Type{GetVarTypeResponse}, name::Symbol, val)
  if name === Symbol("type")
    OpenAPI.validate_param(
      name,
      "GetVarTypeResponse",
      :enum,
      val,
      ["float", "double", "int32", "int64"],
    )
  end
end
