# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""GetTimeUnitsResponse

    GetTimeUnitsResponse(;
        units=nothing,
    )

    - units::String
"""
Base.@kwdef mutable struct GetTimeUnitsResponse <: OpenAPI.APIModel
    units::Union{Nothing, String} = nothing

    function GetTimeUnitsResponse(units, )
        OpenAPI.validate_property(GetTimeUnitsResponse, Symbol("units"), units)
        return new(units, )
    end
end # type GetTimeUnitsResponse

const _property_types_GetTimeUnitsResponse = Dict{Symbol,String}(Symbol("units")=>"String", )
OpenAPI.property_type(::Type{ GetTimeUnitsResponse }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_GetTimeUnitsResponse[name]))}

function check_required(o::GetTimeUnitsResponse)
    o.units === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ GetTimeUnitsResponse }, name::Symbol, val)
    if name === Symbol("units")
        OpenAPI.validate_param(name, "GetTimeUnitsResponse", :minLength, val, 1)
    end
end
