# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


function get_grid_origin_read(handler)
    function get_grid_origin_read_handler(req::HTTP.Request)
        openapi_params = Dict{String,Any}()
        path_params = HTTP.getparams(req)
        openapi_params["grid"] = OpenAPI.Servers.to_param(Int64, path_params, "grid", required=true, )
        req.context[:openapi_params] = openapi_params

        return handler(req)
    end
end

function get_grid_origin_validate(handler)
    function get_grid_origin_validate_handler(req::HTTP.Request)
        openapi_params = req.context[:openapi_params]
        
        return handler(req)
    end
end

function get_grid_origin_invoke(impl; post_invoke=nothing)
    function get_grid_origin_invoke_handler(req::HTTP.Request)
        openapi_params = req.context[:openapi_params]
        ret = impl.get_grid_origin(req::HTTP.Request, openapi_params["grid"];)
        resp = OpenAPI.Servers.server_response(ret)
        return (post_invoke === nothing) ? resp : post_invoke(req, resp)
    end
end

function get_grid_shape_read(handler)
    function get_grid_shape_read_handler(req::HTTP.Request)
        openapi_params = Dict{String,Any}()
        path_params = HTTP.getparams(req)
        openapi_params["grid"] = OpenAPI.Servers.to_param(Int64, path_params, "grid", required=true, )
        req.context[:openapi_params] = openapi_params

        return handler(req)
    end
end

function get_grid_shape_validate(handler)
    function get_grid_shape_validate_handler(req::HTTP.Request)
        openapi_params = req.context[:openapi_params]
        
        return handler(req)
    end
end

function get_grid_shape_invoke(impl; post_invoke=nothing)
    function get_grid_shape_invoke_handler(req::HTTP.Request)
        openapi_params = req.context[:openapi_params]
        ret = impl.get_grid_shape(req::HTTP.Request, openapi_params["grid"];)
        resp = OpenAPI.Servers.server_response(ret)
        return (post_invoke === nothing) ? resp : post_invoke(req, resp)
    end
end

function get_grid_spacing_read(handler)
    function get_grid_spacing_read_handler(req::HTTP.Request)
        openapi_params = Dict{String,Any}()
        path_params = HTTP.getparams(req)
        openapi_params["grid"] = OpenAPI.Servers.to_param(Int64, path_params, "grid", required=true, )
        req.context[:openapi_params] = openapi_params

        return handler(req)
    end
end

function get_grid_spacing_validate(handler)
    function get_grid_spacing_validate_handler(req::HTTP.Request)
        openapi_params = req.context[:openapi_params]
        
        return handler(req)
    end
end

function get_grid_spacing_invoke(impl; post_invoke=nothing)
    function get_grid_spacing_invoke_handler(req::HTTP.Request)
        openapi_params = req.context[:openapi_params]
        ret = impl.get_grid_spacing(req::HTTP.Request, openapi_params["grid"];)
        resp = OpenAPI.Servers.server_response(ret)
        return (post_invoke === nothing) ? resp : post_invoke(req, resp)
    end
end


function registerUniformRectilinearApi(router::HTTP.Router, impl; path_prefix::String="", optional_middlewares...)
    HTTP.register!(router, "GET", path_prefix * "/get_grid_origin/{grid}", OpenAPI.Servers.middleware(impl, get_grid_origin_read, get_grid_origin_validate, get_grid_origin_invoke; optional_middlewares...))
    HTTP.register!(router, "GET", path_prefix * "/get_grid_shape/{grid}", OpenAPI.Servers.middleware(impl, get_grid_shape_read, get_grid_shape_validate, get_grid_shape_invoke; optional_middlewares...))
    HTTP.register!(router, "GET", path_prefix * "/get_grid_spacing/{grid}", OpenAPI.Servers.middleware(impl, get_grid_spacing_read, get_grid_spacing_validate, get_grid_spacing_invoke; optional_middlewares...))
    return router
end
