name = "RemoteBMI"
uuid = "4b6948d5-498c-54b5-b082-cdb1540453e9"
authors = ["Stefan Verhoeven <s.verhoeven@esciencecenter.nl> and contributors"]
version = "0.1.0"

[deps]
BasicModelInterface = "59605e27-edc0-445a-b93d-c09a3a50b330"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
OpenAPI = "d5e62ea6-ddf3-4d43-8e4c-ad5e6c8bfd7d"
TimeZones = "f269a46b-ccf7-5d73-abea-4c690281aa53"
URIs = "5c2747f8-b7ea-4ff2-ba2e-563bfd36b1d4"

[compat]
julia = "1.10"
BasicModelInterface = "0.1.0"
HTTP = "1"
JSON = "0.21.4"
OpenAPI = "0.1"
TimeZones = "1"
URIs = "1"
