name: Julia test

on:
  push:
    branches:
      - main
    tags: ["*"]
    paths:
        - "RemoteBMI.jl/**"
        - .github/workflows/julia-test.yml
  workflow_dispatch:
  pull_request_target:
    paths:
      - "RemoteBMI.jl/**"
      - .github/workflows/julia-test.yml

jobs:
  test:
    uses: ./.github/workflows/JuliaReusableTest.yml
    with:
      os: ${{ matrix.os }}
      version: ${{ matrix.version }}
      arch: ${{ matrix.arch }}
      allow_failure: ${{ matrix.allow_failure }}
      run_codecov: ${{ matrix.version == '1' && matrix.os == 'ubuntu-latest' }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - "lts"
          - "1"
        os:
          - ubuntu-latest
        arch:
          - x64
        allow_failure: [false]
