name: Validate OpenAPI.yaml

on:
  push:
    paths:
      - "openapi.yaml"
      - .github/workflows/openapi.yml
  pull_request_target:
    paths:
      - "openapi.yaml"
      - .github/workflows/openapi.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lintspec:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            openapi.yaml
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Lint OpenAPI with Redocly
        run: npx --package @redocly/cli@latest redocly lint openapi.yaml

      - name: Lint OpenAPI with Spectral
        run: npx --package @stoplight/spectral-cli spectral lint openapi.yaml

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install yamllint
        run: pip install yamllint

      - name: Yamllint
        run: yamllint openapi.yaml
