name: Python

on:
  push:
    paths:
      - "openapi.yaml"
      - "python/remotebmi/**"
      - "python/tests/**"
      - .github/workflows/python.yml
  pull_request_target:
    paths:
      - "openapi.yaml"
      - "python/remotebmi/**"
      - "python/tests/**"
      - .github/workflows/python.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    working-directory: python

jobs:
  lint-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"
      - name: Install ruff
        run: pip install ruff
      - name: Run ruff check
        run: ruff check
      - name: Run ruff format
        run: ruff format --check
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"
      - name: Install dependencies
        run: pip install -e .[dev]
      - name: Run tests
        run: pytest tests
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"
      - name: Install build
        run: pip install build
      - name: Build package
        run: python3 -m build
