# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""GetGridTypeResponse

    GetGridTypeResponse(;
        type=nothing,
    )

    - type::String
"""
Base.@kwdef mutable struct GetGridTypeResponse <: OpenAPI.APIModel
    type::Union{Nothing, String} = nothing

    function GetGridTypeResponse(type, )
        OpenAPI.validate_property(GetGridTypeResponse, Symbol("type"), type)
        return new(type, )
    end
end # type GetGridTypeResponse

const _property_types_GetGridTypeResponse = Dict{Symbol,String}(Symbol("type")=>"String", )
OpenAPI.property_type(::Type{ GetGridTypeResponse }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_GetGridTypeResponse[name]))}

function check_required(o::GetGridTypeResponse)
    o.type === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ GetGridTypeResponse }, name::Symbol, val)
    if name === Symbol("type")
        OpenAPI.validate_param(name, "GetGridTypeResponse", :enum, val, ["scalar", "points", "vector", "unstructured", "structured_quadrilateral", "rectilinear", "uniform_rectilinear"])
    end
end
