# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""InitializeRequest

    InitializeRequest(;
        config_file=nothing,
    )

    - config_file::String : Path to the configuration file. Should resolvable by web service. 
"""
Base.@kwdef mutable struct InitializeRequest <: OpenAPI.APIModel
    config_file::Union{Nothing, String} = nothing

    function InitializeRequest(config_file, )
        OpenAPI.validate_property(InitializeRequest, Symbol("config_file"), config_file)
        return new(config_file, )
    end
end # type InitializeRequest

const _property_types_InitializeRequest = Dict{Symbol,String}(Symbol("config_file")=>"String", )
OpenAPI.property_type(::Type{ InitializeRequest }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_InitializeRequest[name]))}

function check_required(o::InitializeRequest)
    o.config_file === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ InitializeRequest }, name::Symbol, val)
    if name === Symbol("config_file")
        OpenAPI.validate_param(name, "InitializeRequest", :minLength, val, 0)
    end
end
